import { LancamentoProducao, LancamentoParada } from './types';

export function getDemoLancamentos(): {
  lancamentosProducao: LancamentoProducao[];
  lancamentosParada: LancamentoParada[];
} {
  const today = new Date();
  const getDayStr = (daysAgo: number) => {
    const d = new Date(today);
    d.setDate(d.getDate() - daysAgo);
    return d.toISOString().split('T')[0];
  };

  const dates = [
    getDayStr(0), // Hoje
    getDayStr(1), // Ontem
    getDayStr(2),
    getDayStr(3),
    getDayStr(4),
    getDayStr(5),
    getDayStr(6),
  ];

  const lancamentosProducao: LancamentoProducao[] = [
    // Hoje - Corte e Solda CS-01 (Luis Otavio)
    {
      id: 'demo-prod-01',
      data: dates[0],
      setorId: 'set-cs',
      maquinaId: 'maq-cs-01',
      operadorId: 'op-01',
      produtoId: 'prod-01',
      turnoId: 'tur-01',
      ordemProducao: 'OP-2026-901',
      quantidadeBrutaKg: 1250,
      quantidadeLiquidaKg: 1222.5,
      refugoKg: 15.0,
      perdaKg: 12.5,
      percentualPerda: 2.2,
      quantidadeUnidades: 48900,
      quantidadeCaixas: 14,
      unidadesPorCaixa: 3500,
      horaInicio: '06:00',
      horaFim: '14:20',
      tempoTrabalhadoMinutos: 465,
      tempoParadoMinutos: 35,
      produtividadeKgHora: 157.7,
      status: 'concluido',
      observacoes: 'Produção regular de Coletor Adulto. Ajuste fino de solda no início.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Hoje - Corte e Solda CS-02 (Kauan Paladini)
    {
      id: 'demo-prod-02',
      data: dates[0],
      setorId: 'set-cs',
      maquinaId: 'maq-cs-02',
      operadorId: 'op-02',
      produtoId: 'prod-02',
      turnoId: 'tur-01',
      ordemProducao: 'OP-2026-902',
      quantidadeBrutaKg: 980,
      quantidadeLiquidaKg: 961.4,
      refugoKg: 8.0,
      perdaKg: 10.6,
      percentualPerda: 1.9,
      quantidadeUnidades: 32000,
      quantidadeCaixas: 9,
      unidadesPorCaixa: 3500,
      horaInicio: '06:00',
      horaFim: '14:20',
      tempoTrabalhadoMinutos: 460,
      tempoParadoMinutos: 40,
      produtividadeKgHora: 125.4,
      status: 'concluido',
      observacoes: 'Excelente aproveitamento de material em Coletor Infantil.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Hoje - Impressão IMP-01 (Marcos Impressão)
    {
      id: 'demo-prod-03',
      data: dates[0],
      setorId: 'set-imp',
      maquinaId: 'maq-imp-01',
      operadorId: 'op-imp-01',
      produtoId: 'prod-imp-01',
      turnoId: 'tur-01',
      ordemProducao: 'OP-2026-805',
      cliente: 'Hospital São Lucas',
      metragemLinearMetros: 14500,
      quantidadeBrutaKg: 2100,
      quantidadeLiquidaKg: 2053.8,
      refugoKg: 28.0,
      perdaKg: 18.2,
      percentualPerda: 2.2,
      horaInicio: '06:00',
      horaFim: '14:20',
      tempoTrabalhadoMinutos: 440,
      tempoParadoMinutos: 60,
      produtividadeKgHora: 280.1,
      status: 'concluido',
      observacoes: 'Acerto de pantone e clichês no início.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Ontem - Corte e Solda CS-01 (Luis Otavio)
    {
      id: 'demo-prod-04',
      data: dates[1],
      setorId: 'set-cs',
      maquinaId: 'maq-cs-01',
      operadorId: 'op-01',
      produtoId: 'prod-01',
      turnoId: 'tur-01',
      ordemProducao: 'OP-2026-898',
      quantidadeBrutaKg: 1300,
      quantidadeLiquidaKg: 1276.6,
      refugoKg: 12.0,
      perdaKg: 11.4,
      percentualPerda: 1.8,
      quantidadeUnidades: 51000,
      quantidadeCaixas: 15,
      unidadesPorCaixa: 3500,
      horaInicio: '06:00',
      horaFim: '14:20',
      tempoTrabalhadoMinutos: 475,
      tempoParadoMinutos: 25,
      produtividadeKgHora: 161.2,
      status: 'concluido',
      observacoes: 'Ritmo acelerado, aparas mínimas.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Ontem - Corte e Solda CS-02 (Caio Felipe)
    {
      id: 'demo-prod-05',
      data: dates[1],
      setorId: 'set-cs',
      maquinaId: 'maq-cs-02',
      operadorId: 'op-03',
      produtoId: 'prod-02',
      turnoId: 'tur-02',
      ordemProducao: 'OP-2026-899',
      quantidadeBrutaKg: 1020,
      quantidadeLiquidaKg: 998.5,
      refugoKg: 11.0,
      perdaKg: 10.5,
      percentualPerda: 2.1,
      quantidadeUnidades: 33200,
      quantidadeCaixas: 9,
      unidadesPorCaixa: 3500,
      horaInicio: '14:20',
      horaFim: '22:40',
      tempoTrabalhadoMinutos: 455,
      tempoParadoMinutos: 45,
      produtividadeKgHora: 131.7,
      status: 'concluido',
      observacoes: 'Ajuste de temperatura na solda lateral.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Ontem - Extrusora EXT-01 (Anderson Extrusão)
    {
      id: 'demo-prod-06',
      data: dates[1],
      setorId: 'set-ext',
      maquinaId: 'maq-ext-01',
      operadorId: 'op-ext-01',
      produtoId: 'prod-ext-01',
      turnoId: 'tur-01',
      ordemProducao: 'OP-2026-850',
      quantidadeBrutaKg: 620,
      quantidadeLiquidaKg: 608.2,
      refugoKg: 7.0,
      perdaKg: 4.8,
      percentualPerda: 1.9,
      horaInicio: '06:00',
      horaFim: '14:20',
      tempoTrabalhadoMinutos: 470,
      tempoParadoMinutos: 30,
      produtividadeKgHora: 77.6,
      status: 'concluido',
      observacoes: 'Extrusão de bobina tubular PEBD virgem.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Dias anteriores
    {
      id: 'demo-prod-07',
      data: dates[2],
      setorId: 'set-cs',
      maquinaId: 'maq-cs-01',
      operadorId: 'op-01',
      produtoId: 'prod-01',
      turnoId: 'tur-01',
      ordemProducao: 'OP-2026-880',
      quantidadeBrutaKg: 1280,
      quantidadeLiquidaKg: 1254.4,
      refugoKg: 14.0,
      perdaKg: 11.6,
      percentualPerda: 2.0,
      quantidadeUnidades: 50100,
      quantidadeCaixas: 14,
      unidadesPorCaixa: 3500,
      horaInicio: '06:00',
      horaFim: '14:20',
      tempoTrabalhadoMinutos: 470,
      tempoParadoMinutos: 30,
      produtividadeKgHora: 160.1,
      status: 'concluido',
      observacoes: 'Produção estável dentro da meta.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'demo-prod-08',
      data: dates[3],
      setorId: 'set-cs',
      maquinaId: 'maq-cs-02',
      operadorId: 'op-02',
      produtoId: 'prod-02',
      turnoId: 'tur-01',
      ordemProducao: 'OP-2026-875',
      quantidadeBrutaKg: 950,
      quantidadeLiquidaKg: 928.1,
      refugoKg: 12.0,
      perdaKg: 9.9,
      percentualPerda: 2.3,
      quantidadeUnidades: 31000,
      quantidadeCaixas: 9,
      unidadesPorCaixa: 3500,
      horaInicio: '06:00',
      horaFim: '14:20',
      tempoTrabalhadoMinutos: 445,
      tempoParadoMinutos: 55,
      produtividadeKgHora: 125.1,
      status: 'concluido',
      observacoes: 'Substituição de teflon e aquecimento inicial.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'demo-prod-09',
      data: dates[4],
      setorId: 'set-imp',
      maquinaId: 'maq-imp-01',
      operadorId: 'op-imp-01',
      produtoId: 'prod-imp-01',
      turnoId: 'tur-01',
      ordemProducao: 'OP-2026-820',
      cliente: 'Clínica Vida Segura',
      metragemLinearMetros: 13800,
      quantidadeBrutaKg: 2050,
      quantidadeLiquidaKg: 2004.9,
      refugoKg: 25.0,
      perdaKg: 20.1,
      percentualPerda: 2.2,
      horaInicio: '06:00',
      horaFim: '14:20',
      tempoTrabalhadoMinutos: 455,
      tempoParadoMinutos: 45,
      produtividadeKgHora: 264.4,
      status: 'concluido',
      observacoes: 'Registro de impressão e troca de rolo anilox.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  const lancamentosParada: LancamentoParada[] = [
    {
      id: 'demo-par-01',
      lancamentoProducaoId: 'demo-prod-01',
      data: dates[0],
      maquinaId: 'maq-cs-01',
      operadorId: 'op-01',
      turnoId: 'tur-01',
      motivoParadaId: 'mot-01', // Setup
      tempoMinutos: 20,
      horaInicio: '06:00',
      horaFim: '06:20',
      observacoes: 'Troca de bobina tubular PEBD 0,08',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'demo-par-02',
      lancamentoProducaoId: 'demo-prod-01',
      data: dates[0],
      maquinaId: 'maq-cs-01',
      operadorId: 'op-01',
      turnoId: 'tur-01',
      motivoParadaId: 'mot-02', // Ajuste
      tempoMinutos: 15,
      horaInicio: '11:40',
      horaFim: '11:55',
      observacoes: 'Substituição e limpeza do teflon da régua de solda',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'demo-par-03',
      lancamentoProducaoId: 'demo-prod-03',
      data: dates[0],
      maquinaId: 'maq-imp-01',
      operadorId: 'op-imp-01',
      turnoId: 'tur-01',
      motivoParadaId: 'mot-01', // Setup
      tempoMinutos: 45,
      horaInicio: '08:00',
      horaFim: '08:45',
      observacoes: 'Setup de clichês e acerto de cores para cliente hospitalar',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'demo-par-04',
      lancamentoProducaoId: 'demo-prod-05',
      data: dates[1],
      maquinaId: 'maq-cs-02',
      operadorId: 'op-03',
      turnoId: 'tur-02',
      motivoParadaId: 'mot-02', // Ajuste
      tempoMinutos: 20,
      horaInicio: '16:10',
      horaFim: '16:30',
      observacoes: 'Troca de bobina e regulagem de tensão no desbobinador',
      createdAt: new Date().toISOString(),
    },
  ];

  return { lancamentosProducao, lancamentosParada };
}
